### ISSUE TITLE
Postgres backup fails

### ISSUE THREAD

**Issue by shon** [rakeshgunduka/s3_dumps#3]
ENV:

OS: Ubuntu Linux 18.04
Python: 3.6.5

```shell
$ sudo apt-get install python3-pip
$ sudo pip install s3_dumps
$ /usr/local/bin/postgres_to_s3.py --ACCESS_KEY='xxxx' --SECRET='xxx' \
 --BUCKET_NAME='my-backup' --FILE_KEY='server/postgres' --backup  --archive \
 --SERVICE_NAME amazon
```

```python
Traceback (most recent call last):
  File "/usr/local/bin/postgres_to_s3.py", line 114, in <module>
    archive.archive()
  File "/usr/local/lib/python3.6/dist-packages/s3_dumps/archive.py", line 47, in archive
    if self.remove_key(obj):
  File "/usr/local/lib/python3.6/dist-packages/s3_dumps/archive.py", line 78, in remove_key
    if obj.month_delta.day == 1:
AttributeError: 's3.ObjectSummary' object has no attribute 'month_delta'

```

**Comment by rakeshgunduka** [comment]
@shon Thanks for reporting. Its a typo error. @rajatsingla has committed a patch which should resolve the problem.

**Comment by rakeshgunduka** [comment]
[This PR](https://github.com/rakeshgunduka/s3_dumps/pull/4) resolve the issue. So going forward and closing it. Please reopen the issue if the problem still persists.
